/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotfifai.ui;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import spotfifai.controller.HomeController;
import spotfifai.models.Song;
import spotfifai.util.located.ServiceLocator;

/**
 *
 * @author admin
 */
public class HomeForm extends javax.swing.JPanel
{
    final HomeController homeController;
    /**
     * Creates new form HomeForm
     */
    public HomeForm()
    {
        initComponents();
        
        homeController = ServiceLocator.get(HomeController.class);

        this.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5); 
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1;

        int cols = 3; 
        var topSongs = homeController.loadTopSongs();
        for (int i = 0; i < topSongs.size(); i++)
        {
            Song song = topSongs.get(i);
            var musicItem = new MusicItemForm(song);
            gbc.gridx = i % cols;
            gbc.gridy = i / cols;
            this.add(musicItem, gbc);
        }

        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
