/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotfifai.ui;

import javax.swing.Icon;
import spotfifai.util.theme.Theme;

/**
 *
 * @author admin
 */
public class MenuItemForm extends javax.swing.JPanel
{
    Runnable onClick;
    Runnable onSelect;
    boolean isSelected;
    /**
     * Creates new form PlaylistItemForm
     */
    public MenuItemForm(String title, String subTitle, Icon icon, Runnable onClick)
    {
        initComponents();
        setVisible(true);
        
        labelTitle.setText(title);
        labelSubTitle.setText(subTitle);
        labelIcon.setIcon(icon);
        
        this.onClick = onClick;
    }
    
    public void setOnSelected(Runnable onSelect)
    {
        this.onSelect = onSelect;
    }
    
    public void setSelection(boolean state)
    {
        isSelected = state;
        if(!isSelected)
            panelTabItem.setBackground(Theme.DARK_COLOR);
        else 
            panelTabItem.setBackground(Theme.GRAY_DARK_COLOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelTabItem = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelSubTitle = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();

        setOpaque(false);

        panelTabItem.setBackground(new java.awt.Color(35, 35, 35));
        panelTabItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelTabItem.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                panelTabItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                panelTabItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                panelTabItemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                panelTabItemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                panelTabItemMouseReleased(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelTitle.setText("Menu Title");

        labelSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        labelSubTitle.setText("sub menu title");

        labelIcon.setBackground(new java.awt.Color(45, 45, 45));
        labelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/playlist_icon.png"))); // NOI18N
        labelIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelIcon.setFocusable(false);
        labelIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelIcon.setOpaque(true);
        labelIcon.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout panelTabItemLayout = new javax.swing.GroupLayout(panelTabItem);
        panelTabItem.setLayout(panelTabItemLayout);
        panelTabItemLayout.setHorizontalGroup(
            panelTabItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTabItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelSubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        panelTabItemLayout.setVerticalGroup(
            panelTabItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabItemLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelTabItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTabItemLayout.createSequentialGroup()
                        .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelSubTitle)))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelTabItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(panelTabItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelTabItemMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_panelTabItemMouseClicked
    {//GEN-HEADEREND:event_panelTabItemMouseClicked
        this.onClick.run();
        this.onSelect.run();
    }//GEN-LAST:event_panelTabItemMouseClicked

    private void panelTabItemMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_panelTabItemMouseEntered
    {//GEN-HEADEREND:event_panelTabItemMouseEntered
        panelTabItem.setBackground(Theme.GRAY_DARK_COLOR);
    }//GEN-LAST:event_panelTabItemMouseEntered

    private void panelTabItemMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_panelTabItemMouseExited
    {//GEN-HEADEREND:event_panelTabItemMouseExited
        panelTabItem.setBackground(isSelected? Theme.GRAY_DARK_COLOR : Theme.DARK_COLOR);
    }//GEN-LAST:event_panelTabItemMouseExited

    private void panelTabItemMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_panelTabItemMousePressed
    {//GEN-HEADEREND:event_panelTabItemMousePressed
        panelTabItem.setBackground(Theme.DARKER_COLOR);
    }//GEN-LAST:event_panelTabItemMousePressed

    private void panelTabItemMouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_panelTabItemMouseReleased
    {//GEN-HEADEREND:event_panelTabItemMouseReleased
        panelTabItem.setBackground(Theme.GRAY_DARK_COLOR);
    }//GEN-LAST:event_panelTabItemMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelSubTitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelTabItem;
    // End of variables declaration//GEN-END:variables
}
