/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotfifai.ui.auth;

import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import spotfifai.controller.SpotfifaiAuth;
import spotfifai.controller.UserController;
import spotfifai.models.User;
import spotfifai.ui.SongEditorForm;
import spotfifai.util.ImageUtil;
import spotfifai.util.located.ServiceLocator;

/**
 *
 * @author admin
 */
public class AccountManagementForm extends javax.swing.JPanel
{

    UserController userController;
    boolean isEditing;

    /**
     * Creates new form AccountManagementForm
     */
    public AccountManagementForm()
    {
        initComponents();
        userController = ServiceLocator.get(UserController.class);
        showUserInfo(SpotfifaiAuth.current().getCurrentUser());
    }

    private void showUserInfo(User u)
    {
        labelUID.setText("UID: " + u.getUserId());
        txtFieldUserName.setText(u.getUsername());
        txtFieldUserName.setEditable(isEditing);
        passwordField.setText(u.getPassword());
        passwordField.setEditable(isEditing);
        buttonEdition.setText("Edit");
        labelIcon.setIcon(ImageUtil.getIcon(u.getIconData(), 80, 80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonEdition = new javax.swing.JButton();
        labelIcon = new javax.swing.JLabel();
        txtFieldUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        buttonSignout = new javax.swing.JButton();
        labelUID = new javax.swing.JLabel();

        buttonEdition.setText("Edit");
        buttonEdition.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonEditionActionPerformed(evt);
            }
        });

        labelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/fifai.png"))); // NOI18N
        labelIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelIcon.setPreferredSize(new java.awt.Dimension(80, 80));
        labelIcon.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelIconMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setLabelFor(passwordField);
        jLabel3.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                passwordFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setLabelFor(txtFieldUserName);
        jLabel4.setText("Username");

        buttonSignout.setText("SIGN OUT");
        buttonSignout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonSignoutActionPerformed(evt);
            }
        });

        labelUID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUID.setText("UID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(buttonSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(labelUID)
                            .addComponent(jLabel3)
                            .addComponent(txtFieldUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                            .addComponent(passwordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(buttonEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUID)
                .addGap(7, 7, 7)
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonSignout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEditionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonEditionActionPerformed
    {//GEN-HEADEREND:event_buttonEditionActionPerformed
        if (isEditing)
        {
            User u = SpotfifaiAuth.current().getCurrentUser();
            
            String newUserName = txtFieldUserName.getText();
            String newPassword = new String(passwordField.getPassword());
            if(!SpotfifaiAuth.current().checkLength(newUserName))
            {
                JOptionPane.showMessageDialog(null, "Username must at least 8 characters long.", 
                        "Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(!SpotfifaiAuth.current().isPasswordValid(newPassword))
            {
                JOptionPane.showMessageDialog(null, "Password must at least 8 characters long and contain at least one number..", 
                        "Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            u.setUsername(newUserName);
            u.setPassword(newPassword);
            userController.updateUser(u);
            showUserInfo(u);
        } else
        {
            buttonEdition.setText("Save");
        }

        isEditing = !isEditing;
        txtFieldUserName.setEditable(isEditing);
        passwordField.setEditable(isEditing);
    }//GEN-LAST:event_buttonEditionActionPerformed

    private void buttonSignoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonSignoutActionPerformed
    {//GEN-HEADEREND:event_buttonSignoutActionPerformed
        SpotfifaiAuth.current().signOut();
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_buttonSignoutActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_passwordFieldActionPerformed
    {//GEN-HEADEREND:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void labelIconMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelIconMouseClicked
    {//GEN-HEADEREND:event_labelIconMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter restrict = new FileNameExtensionFilter("Image files (JPG, JPEG, PNG)", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(restrict);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                User u = SpotfifaiAuth.current().getCurrentUser();
                byte[] iconData = Files.readAllBytes(fileChooser.getSelectedFile().toPath());
                u.setIconData(iconData);
                labelIcon.setIcon(new ImageIcon(iconData));

            } catch (IOException ex)
            {
                Logger.getLogger(SongEditorForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_labelIconMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdition;
    private javax.swing.JButton buttonSignout;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelUID;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtFieldUserName;
    // End of variables declaration//GEN-END:variables
}
