CREATE DATABASE SPOTFIFAI

USE SPOTFIFAI

CREATE TABLE [User]
(
	userId CHAR(10) NOT NULL PRIMARY KEY,
	username NVARCHAR(50),
	password NCHAR(20),
)


CREATE TABLE SONG
(
	songId NVARCHAR(20) NOT NULL PRIMARY KEY,
    title NVARCHAR(100) NOT NULL,
	description NVARCHAR(500),
	audioData VARBINARY(MAX),
	userId CHAR(10) FOREIGN KEY REFERENCES [User](userId)
)


CREATE TABLE Playlist
(
	playlistId INT PRIMARY KEY IDENTITY (1,1),
    title NVARCHAR(100),
	userId CHAR(10) FOREIGN KEY REFERENCES [User](userId)
)

CREATE TABLE PlaylistDetail
(
	playlistId INT NOT NULL,
	songId NVARCHAR(20),
	PRIMARY KEY (playlistId, songId),
	FOREIGN KEY (playlistId) REFERENCES Playlist(playlistId),
	FOREIGN KEY (songId) REFERENCES Song(songId)
)


DROP TABLE PlaylistDetail
DROP TABLE Playlist
DROP TABLE Song
DROP TABLE [User]

SELECT * FROM SONG