/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotfifai.view;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import spotfifai.controller.HomeController;
import spotfifai.models.Song;
import spotfifai.util.located.ServiceLocator;

/**
 *
 * @author admin
 */
public class HomeForm extends javax.swing.JPanel
{

    final HomeController homeController;

    /**
     * Creates new form HomeForm
     */
    public HomeForm()
    {
        initComponents();
        homeController = ServiceLocator.get(HomeController.class);

        panelMusicContainer.setLayout(new GridBagLayout());
        refresh();
    }

    private void refresh()
    {
        panelMusicContainer.removeAll();
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(10, 10, 10, 10);
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.weightx = 1;

        int cols = 4;
        var topSongs = homeController.loadTopSongs();
        for (int i = 0; i < topSongs.size(); i++)
        {
            Song song = topSongs.get(i);
            var musicItem = new MusicItemForm(song);
            gbc.gridx = i % cols;
            gbc.gridy = i / cols;
            panelMusicContainer.add(musicItem, gbc);
        }

        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelMusicContainer = new javax.swing.JPanel();
        buttonRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(50, 50, 50));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);

        panelMusicContainer.setAlignmentX(0.0F);
        panelMusicContainer.setAlignmentY(0.0F);
        panelMusicContainer.setOpaque(false);

        javax.swing.GroupLayout panelMusicContainerLayout = new javax.swing.GroupLayout(panelMusicContainer);
        panelMusicContainer.setLayout(panelMusicContainerLayout);
        panelMusicContainerLayout.setHorizontalGroup(
            panelMusicContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelMusicContainerLayout.setVerticalGroup(
            panelMusicContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMusicContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(buttonRefresh)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(buttonRefresh)
                .addGap(12, 12, 12)
                .addComponent(panelMusicContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonRefreshActionPerformed
    {//GEN-HEADEREND:event_buttonRefreshActionPerformed
        refresh();
    }//GEN-LAST:event_buttonRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JPanel panelMusicContainer;
    // End of variables declaration//GEN-END:variables
}
