/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotfifai.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import spotfifai.controller.MusicPlayerController;
import spotfifai.controller.PlaylistsController;
import spotfifai.controller.SongDistributorController;
import spotfifai.models.Playlist;
import spotfifai.util.located.ServiceLocator;

/**
 *
 * @author admin
 */
public class PlaylistForm extends javax.swing.JPanel
{
    
    PlaylistsController playlistController;
    SongDistributorController songController;
    MusicPlayerController musicPlayer;
    MenuItemForm activeMenuItem;
    Playlist currentPlaylist;

    /**
     * Creates new form PlaylistForm
     */
    public PlaylistForm()
    {
        initComponents();

        playlistController = ServiceLocator.get(PlaylistsController.class);
        songController = ServiceLocator.get(SongDistributorController.class);
        musicPlayer = ServiceLocator.get(MusicPlayerController.class);
        
//        tableSongs.getColumn("Play").setCellRenderer(new ButtonRenderer());
//        tableSongs.getColumn("Play").setCellEditor(new ButtonEditor(tableSongs, e ->
//        {
//            
//        }));
        
        tableSongs.getColumn("Remove").setCellRenderer(new ButtonRenderer());
        tableSongs.getColumn("Remove").setCellEditor(new ButtonEditor(tableSongs, e ->
        {
            playlistController.removeSongFromPlaylist(currentPlaylist.getPlaylistDetails().get(e), currentPlaylist);
            loadPlaylistSongs();
        }));
    }
    

    public void setPlaylist(Playlist playlist, MenuItemForm selectedMenuItem)
    {
        currentPlaylist = playlist;
        activeMenuItem = selectedMenuItem;

        labelTitle.setText(playlist.getTitle());

        loadPlaylistSongs();
    }

    private void loadPlaylistSongs()
    {
        var tableModel = (DefaultTableModel) tableSongs.getModel();
        tableModel.setRowCount(0);

        var songsInPlaylist = songController.getSongs(currentPlaylist.getPlaylistDetails());
        if (songsInPlaylist != null)
        {
            for (var song : songsInPlaylist.values())
            {
                tableModel.insertRow(0, new Object[]
                {
                    song.getTitle(), song.getDescription(), song.getArtistId(), "Remove"
                });
            }
        }

        tableSongs.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        labelCoverIcon = new javax.swing.JLabel();
        buttonDelete = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSongs = new javax.swing.JTable();
        buttonPlayAll = new javax.swing.JButton();

        labelCoverIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCoverIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/anime_wallpaper.jpg"))); // NOI18N
        labelCoverIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        buttonDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonDelete.setText("Remove");
        buttonDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonDeleteActionPerformed(evt);
            }
        });

        labelTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTitle.setText("Playlist#1");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tableSongs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title", "Description", "Artist", "Remove"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tableSongs.setColumnSelectionAllowed(true);
        tableSongs.setRowHeight(50);
        tableSongs.setShowGrid(true);
        tableSongs.setShowVerticalLines(false);
        tableSongs.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableSongs);
        tableSongs.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableSongs.getColumnModel().getColumnCount() > 0)
        {
            tableSongs.getColumnModel().getColumn(3).setResizable(false);
            tableSongs.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        buttonPlayAll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonPlayAll.setText("Play All");
        buttonPlayAll.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonPlayAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCoverIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 872, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPlayAll, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelCoverIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(buttonPlayAll, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonDeleteActionPerformed
    {//GEN-HEADEREND:event_buttonDeleteActionPerformed

        int option = JOptionPane.showConfirmDialog(null, "Delete " + currentPlaylist.getTitle() + " from your library?", "Delete playlist", JOptionPane.OK_CANCEL_OPTION);
        if (option != JOptionPane.OK_OPTION)
        {
            return;
        }

        if (playlistController.onPlaylistDelete(currentPlaylist))
        {
            activeMenuItem.setEnabled(false);
            System.out.println("playlist removed");
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonPlayAllActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonPlayAllActionPerformed
    {//GEN-HEADEREND:event_buttonPlayAllActionPerformed
        musicPlayer.playAPlaylist(currentPlaylist);
    }//GEN-LAST:event_buttonPlayAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonPlayAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCoverIcon;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTable tableSongs;
    // End of variables declaration//GEN-END:variables
}
