/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotfifai.view;

import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import spotfifai.controller.SongDistributorController;
import spotfifai.models.Song;
import spotfifai.util.ImageUtil;
import spotfifai.util.located.ResourceLocator;
import spotfifai.util.located.ServiceLocator;

/**
 *
 * @author admin
 */
public class SongEditorForm extends javax.swing.JPanel
{

    SongDistributorController songDistributor;
    Song tempSong;

    /**
     * Creates new form SongEditorForm
     */
    public SongEditorForm()
    {
        this(null);
    }

    public SongEditorForm(Song song)
    {
        initComponents();
        songDistributor = ServiceLocator.get(SongDistributorController.class);

        // temp song;
        if (song != null)
        {
            tempSong = new Song(song);
        } else
        {
            tempSong = new Song();
            try
            {
                tempSong.setIconData(Files.readAllBytes(ResourceLocator.getDefaultSongIconPath()));
            } catch (IOException ex)
            {
                Logger.getLogger(SongEditorForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        setData(tempSong.getSongId(), tempSong.getTitle(), tempSong.getDescription(), tempSong.getIconData(), tempSong.getTitle() + "(audioBytes).wav");
    }

    public final void setData(String id, String title, String description, byte[] iconData, String filePath)
    {
        System.out.println("edit song!");
        txtFieldSongTitle.setText(title);
        txtFieldSongDescription.setText(description);
        labelId.setText("Auto generated id: " + id);
        labelFilePath.setText(filePath);
        labelIcon.setIcon(ImageUtil.getIcon(iconData, 150, 150));
    }

    private String getSongTitle()
    {
        return txtFieldSongTitle.getText();
    }

    private String getSongDescription()
    {
        return txtFieldSongDescription.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        txtFieldSongTitle = new javax.swing.JTextField();
        txtFieldSongDescription = new javax.swing.JTextField();
        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        buttonChooseFile = new javax.swing.JButton();
        labelFilePath = new javax.swing.JLabel();
        labelIcon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(350, 500));

        jLabel2.setLabelFor(txtFieldSongTitle);
        jLabel2.setText("Title: ");

        txtFieldSongTitle.setText("Song title");

        txtFieldSongDescription.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFieldSongDescription.setText("Song description");
        txtFieldSongDescription.setActionCommand("<Not Set>");
        txtFieldSongDescription.setAlignmentX(0.0F);
        txtFieldSongDescription.setAlignmentY(0.0F);

        buttonOk.setText("Ok");
        buttonOk.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOkActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.setPreferredSize(new java.awt.Dimension(100, 50));
        buttonCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonCancelActionPerformed(evt);
            }
        });

        buttonChooseFile.setText("Choose File");
        buttonChooseFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonChooseFileActionPerformed(evt);
            }
        });

        labelFilePath.setText("choose a .wav file");

        labelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/anime_wallpaper.jpg"))); // NOI18N
        labelIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelIcon.setPreferredSize(new java.awt.Dimension(150, 150));
        labelIcon.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                labelIconMouseClicked(evt);
            }
        });

        jLabel3.setText("Icon: ");

        jLabel4.setLabelFor(txtFieldSongTitle);
        jLabel4.setText("Description: ");

        labelId.setText("Auto Generated ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonChooseFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(labelFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFieldSongTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtFieldSongDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldSongTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldSongDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChooseFile)
                    .addComponent(labelFilePath))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChooseFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonChooseFileActionPerformed
    {//GEN-HEADEREND:event_buttonChooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter restrict = new FileNameExtensionFilter("WAV audio files", "wav");
        fileChooser.setFileFilter(restrict);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                byte[] audioData = Files.readAllBytes(fileChooser.getSelectedFile().toPath());
                tempSong.setAudioData(audioData);
                labelFilePath.setText(fileChooser.getSelectedFile().getPath());

            } catch (IOException ex)
            {
                Logger.getLogger(SongEditorForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_buttonChooseFileActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOkActionPerformed
    {//GEN-HEADEREND:event_buttonOkActionPerformed
        tempSong.setTitle(getSongTitle());
        tempSong.setDescription(getSongDescription());
        
        if(!songDistributor.checkForSong(tempSong))
        {
            JOptionPane.showMessageDialog(null, "Invalid song Data");
            return;
        }
        
        if (!songDistributor.getSongDAO().contains(tempSong))
        {
            //publish
            System.out.println("publish");
            songDistributor.upload(tempSong);
        } else
        {
            //edit
            System.out.println("update");
            if(songDistributor.update(tempSong))
            {
                
            }
        }

        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_buttonOkActionPerformed

    private void labelIconMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_labelIconMouseClicked
    {//GEN-HEADEREND:event_labelIconMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter restrict = new FileNameExtensionFilter("Image files (JPG, JPEG, PNG)", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(restrict);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            try
            {
                byte[] iconData = Files.readAllBytes(fileChooser.getSelectedFile().toPath());
                tempSong.setIconData(iconData);
                labelIcon.setIcon(ImageUtil.getIcon(iconData, 150, 150));
                System.out.println(iconData);

            } catch (IOException ex)
            {
                Logger.getLogger(SongEditorForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_labelIconMouseClicked

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonCancelActionPerformed
    {//GEN-HEADEREND:event_buttonCancelActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonChooseFile;
    private javax.swing.JButton buttonOk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelFilePath;
    private javax.swing.JLabel labelIcon;
    private javax.swing.JLabel labelId;
    private javax.swing.JTextField txtFieldSongDescription;
    private javax.swing.JTextField txtFieldSongTitle;
    // End of variables declaration//GEN-END:variables
}
