/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package spotfifai.ui.songeditor;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import spotfifai.controller.SongDistributorController;
import spotfifai.models.Song;
import spotfifai.util.located.ServiceLocator;

/**
 *
 * @author admin
 */
public class SongEditorForm extends javax.swing.JPanel
{

    SongDistributorController songDistributor;
    File selectedFile;
    Song tempSong;

    /**
     * Creates new form SongEditorForm
     */
    public SongEditorForm()
    {
        this(null);
    }

    public SongEditorForm(Song song)
    {
        initComponents();
        songDistributor = ServiceLocator.get(SongDistributorController.class);

        // temp song;
        if (song != null)
        {
            tempSong = new Song(song);
        } else
        {
            tempSong = new Song();
        }

        setData(tempSong.getSongId(), tempSong.getTitle(), tempSong.getDescription(), tempSong.getTitle() + "(audioBytes).wav");
    }

    public final void setData(String id, String title, String description, String filePath)
    {
        System.out.println("edit song!");
        txtFieldSongTitle.setText(title);
        txtFieldSongDescription.setText(description);
        labelId.setText("Auto generated id: " + id);
        labelFilePath.setText(filePath);
    }

    private String getSongTitle()
    {
        return txtFieldSongTitle.getText();
    }

    private String getSongDescription()
    {
        return txtFieldSongDescription.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel2 = new javax.swing.JLabel();
        txtFieldSongTitle = new javax.swing.JTextField();
        txtFieldSongDescription = new javax.swing.JTextField();
        buttonOk = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonChooseFile = new javax.swing.JButton();
        labelFilePath = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(463, 500));

        jLabel2.setLabelFor(txtFieldSongTitle);
        jLabel2.setText("Title: ");

        txtFieldSongTitle.setText("Song title");
        txtFieldSongTitle.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtFieldSongTitleActionPerformed(evt);
            }
        });

        txtFieldSongDescription.setText("Song description");

        buttonOk.setText("Ok");
        buttonOk.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOkActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        buttonChooseFile.setText("Choose File");
        buttonChooseFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonChooseFileActionPerformed(evt);
            }
        });

        labelFilePath.setText("choose a .wav file");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/anime_wallpaper.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabel3.setText("Icon: ");

        jLabel4.setLabelFor(txtFieldSongTitle);
        jLabel4.setText("Description: ");

        labelId.setText("Auto Generated ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtFieldSongDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(txtFieldSongTitle, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buttonChooseFile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldSongTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldSongDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChooseFile)
                    .addComponent(labelFilePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonChooseFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonChooseFileActionPerformed
    {//GEN-HEADEREND:event_buttonChooseFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter restrict = new FileNameExtensionFilter("WAV audio files", "wav");
        fileChooser.setFileFilter(restrict);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION)
        {
            selectedFile = fileChooser.getSelectedFile();
            labelFilePath.setText(selectedFile.getAbsolutePath());
        }

    }//GEN-LAST:event_buttonChooseFileActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOkActionPerformed
    {//GEN-HEADEREND:event_buttonOkActionPerformed
        try
        {
            tempSong.setTitle(getSongTitle());
            tempSong.setDescription(getSongDescription());

            if (!songDistributor.getSongDAO().contains(tempSong))
            {
                //publish
                tempSong.setAudioData(Files.readAllBytes(selectedFile.toPath()));
                songDistributor.upload(tempSong);
            } 
            else
            {
                //edit
                if(selectedFile != null)
                        tempSong.setAudioData(Files.readAllBytes(selectedFile.toPath()));
                songDistributor.getSongDAO().update(tempSong);
            }

        } catch (IOException ex)
        {
            Logger.getLogger(SongEditorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setEnabled(false);
    }//GEN-LAST:event_buttonOkActionPerformed

    private void txtFieldSongTitleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtFieldSongTitleActionPerformed
    {//GEN-HEADEREND:event_txtFieldSongTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSongTitleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChooseFile;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelFilePath;
    private javax.swing.JLabel labelId;
    private javax.swing.JTextField txtFieldSongDescription;
    private javax.swing.JTextField txtFieldSongTitle;
    // End of variables declaration//GEN-END:variables
}
